var dotenv = require("dotenv").config();
var fb = require("fb");
fb.setAccessToken(process.env.TOKEN);

// Generate quotes
var prompts = [
    "{A}: I’m going to take you out \n {B}: great, it’s a date! \n {A}: I meant that as a threat. \n {B}: See you at five!",
    "{A}: So what’s for dinner? \n {B}, staring at the food they just burnt: Regret.",
    "{A}: Is letting someone win at chess sapiosexual bottoming \n {B}: Does anyone in this godforsaken group ever think before they speak",
    "{A}: I think I'm having a mid-life crisis. \n {B}: You're like 15 years old \n {A}: I MIGHT DIE AT 30!",
    "{A}: Man, I only ever see you awake, do you ever shut down or stop running? \n {B}: Oh, I’m always running \n {B}: The question is from what",
    "{A}: What the fuck is wrong with you?! \n {B}: Wow, you could start with a 'good morning'. \n {A}: Good morning. What the fuck is wrong with you?!",
    "{A}: WHAT’S YOUR TYPE \n {B}: Anything, honestly, but nerds especially \n {A}, desperately, as {B} bleeds out: <b><i>YOUR BLOOD TYPE</b></i> \n {B}: Oh! B positive. \n {A}: DONT TRY TO CHEER ME UP JUST TELL ME YOUR BLOOD TYPE \n {B}:",
    "{A}: *holding a bottle* Is this whiskey or perfume? \n {B}: *chugs entire bottle* \n {B}: It’s perfume.",
    "{A}: Top 30 reasons why {A} is sorry... Number 5 will surprise you! \n {B}: Top 30 anime deaths. Number One: YOUR FUCKING ASS RIGHT NOW!!!",
    "{A}: I want to wake up with you every day for the rest of our lives \n {B}: I wake up at 4:30 AM \n {A}: \n {A}: I want to see you at some point every day for the rest of our lives",
    "{A}: You often use humor to deflect trauma \n {B}: Thank you \n {A}: I didn't say that was a good thing \n {B}: What I'm hearing is, you think I'm funny",
    "{A}: Go to Hell \n {B}, tearing up: I wish I could",
    "{A}, pointing: May I sit there? \n {B}: That's my lap \n {A}: That doesn't answer my question, {B}.",
    "{A}: Welcome, fellow idiots \n {B}: Hello, {A} \n {A}: No, no, not you, you're not an idiot \n {B}: You underestimate me",
    "{A}: If you were to vacuum up jello through a metal tube, well I think that’d be a neat noise \n {B}: I beg to differ \n {A}: Then Beg",
    "{A}: You know, I'm starting to regret showing you how that blender works. \n {B}, drinking toast: Why do you say that?",
    "{A}: Am I going too far? \n {B}: No, no, no. You went too far about seven hours ago. Now you're going to prison.",
    "{A}: *Walking in to a room* Sorry I’m late... I was... doing things. \n *Sounds of running footsteps progressively getting louder* \n {B}: *Out of breath* THEY PUSHED ME DOWN THE FUCKIN’ STAIRS.",
    "{A}, watching the news: Someone tried to fight a squid at the aquarium today! \n {B}: *walks in covered with ink* Well, maybe the squid was being a dick.",
    "{A}: What if the 'g' in 'gif' is silent? \n {B}: Go the fuck to sleep \n {A}: What gif I don't want to? \n {B}: Fuck You",
    "{A}: This is a mistake \n {B}, enthusiastically: A mistake we're going to laugh about one day! \n {A}: But not today \n {B}, still enthusiastic: Oh, no. Today's going to be a mess",
    "{A}: Hey, you want some leftovers? \n {B}: What's that? \n {A}: You've never had leftovers??? \n {B}: No, because I'm not a quitter.",
    "{A}, tending to {B}'s wounds: How would you rate your pain? \n {B}: Zero stars. Would NOT recommend.",
    "{A}: petition to remove the 'd' from Wednesday \n {B}: Wednesay \n {A}: Not what I had in mind, but I'm flexible",
    "{A}, trying to cheer the group up: Things could be worse, you know! \n {B}: How? \n {A}: How what? \n {B}: How could they be worse? \n {A}: They couldn’t, I lied. \n {B}:",
    "{A}: Can you please be serious for five minutes? \n {B}: My record is four, but I think I can do it.",
    "{A}: Lol heads up if you try to make a candle with food coloring, the food coloring will just sink to the bottom of the glass, and when the flame eventually reaches the bottom all the food coloring will catch fire and become one giant tall flame that you cannot possibly blow out and the glass will start to crack and then you'll throw your tea on it in a panic and then the extremely hot food coloring will boil and sizzle horribly and then the glass will shatter. Please take my word on this lmfao \n {B}: What did you do op? \n {A}: A MISTAKE",
    "{A}: Look. I may not be a saint, but it's not like I’ve killed anybody. I’m not an arsonist. I’ve never found a wallet outside of an IHOP and thought about returning it but saw the owner lived out of state so just took the cash and dropped the wallet back on the ground. \n {B}: Okay, that's really specific, and that makes me think that you definitely did do that.",
    "{A}: A theif. \n {B}: Thief? \n {A}: Theif. \n {B}: I before E, except after C. \n {A}: Thceif. \n {A}: No.",
    "{A}: You know, not every problem can be solved with a sword. \n {B}: That's why I carry two swords.",
    "{A}: God, give me patience. \n {B}: I think you mean 'give me strength'. \n {A}: If God gave me strength, you'd be dead.",
    "{A}: I am not out of control! I'm a law abiding citizen! \n {B}: Really? Name one law \n {A}: Don't kill people? \n {B}: That's on me. I set the bar too low.",
    "{A}: Jail is no fun. I’ll tell you that much. \n {B}: Oh, you’ve been? \n {A}: Once. In Monopoly.",
    "{A}: Hey, it's your turn to wash dishes. \n {B}: I'LL WASH THE WALLS RED WITH YOUR BLOOD. \n {A}: 'Kay, but before that, wash the dishes, also use soap this time?",
    "{A}: {B} and I have the kind of easy chemistry where we finish each other's- \n {B}: Sentences. \n {A}: Don't interrupt me.",
    "{A}, addressing the squad: And if you have any suggestions feel free to put them in the suggestion box. \n {B}: But – that’s just a trash can. \n {A}: It sure is!",
    "{A}: I've already sent good vibes your way… they’re coming. There’s nothing you can do to stop them. \n {B}: This is the most threatening way I’ve ever been cheered up.",
    "{A}: I was thinking I'd do some magic-\n{B}: You? <i>Magic</i>? {A}, it says talent show.",
    "{A}: Is something burning?\n{B}: Just my love for you.\n{A}: {B}, the toaster is on fire.",
    "{A}: I learned some very valuable lessons from this.\n{B}: I’m guessing they are all horrible distortions on the lessons you actually should’ve taken away.\n{A}: Death isn’t real, and I’m basically God.",
    "{A}: Where are you going?\n{B}: To get ice cream or commit a felony, I’ll decide on the way there",
    "{A}: Bad things keep happening to me, like I have bad luck or something.\n{B}: {A}, you don't have bad luck. The reason bad things happen to you is because you're a dumbass.",
    "{A}: How many kids do you have?\n{B}: Biologically, emotionally, or legally?",
    "{A}: {B}... Why did you draw a pentagram on the floor?\n{B}: Your text told me to satanize the house before you returned.\n{A}:\n{A}: I wrote sanitize, {B}.",
    "{A}: *Stubs their toe* FUCK!\n{B}: Mind your language!\n{A}: What else am I supposed to say, “Woe is I”???\n{B}:\n{A}: You have to accept that swear words are necessary sometimes.",
    "{A}, in a beach shirt: So sue me, it's October and I'd like to be on Island Time for a day!\n{B}: I have Spotify open right now on my computer, do you want me to blast you? Do you want me to put you on blast? Cuz I've got your history right here on the sidebar,\n{B}: Take it Back by Jimmy Buffet, Nautical Wheelers by Jimmy Buffet, Jolly Mon Sing by Jimmy Buffet, Steamer by Jimmy Buffet, trEAT HER LIKE A LADY BY JIMMY BUFFET, MAÑANA BY JIMMY BUFFET, WHEN SALOME PLAYS THE DRUMS BY <b><i>JAMES BUFFET</b></i>, HAVANA DAYDREAMIN BY JIMMY BUFFET- What the <i>FUCK</i> happened to you?!\n{A}, laughing: I HAD A CASE OF THE MONDAYS\n{B}: ARE YOU HAUNTED?! ARE YOU FUCKING <i>POSSESSED</i>?!\n{B}: <b><i>YOU USED TO BE MY FRIEND</b></i>\n{A}, cry-laughing: ᴵ ᴴᴬᴰ ᴬ ᶜᴬˢᴱ ᴼᶠ ᵀᴴᴱ ᴹᴼᴺᴰᴬʸˢ",
    "{A}: You're right.\n{B}: That's... That's an unusual phrase for you. Did you just learn it?",
    "{A}: You love me, right, {B}?\n{B}: Normally, I’d say yes without hesitation, but I feel like this is going somewhere and I don’t like it.",
    "{A}: Okay, help me please!\n{B}: Got two words for you.\n{A}: I bet they won't be helpful.\n{B}: Your problem.\n{A}: I was right",
    "{A}: So what do you do?\n{B}: I work in genetic research, and I'm currently trying to eliminate all Cancers.\n{A}: Wow, impressive.\n{B}: Then I'll move on to Leos.",
    "{A}: Treat spiders the way you want to be treated.\n{B}: Killed without hesitation.\n{A}: No.",
    "{A}: Stop buying plastic skeletons for Halloween! It's terrible for the environment!\n{B}: Yeah! Locally sourced, all natural skeletons are much more environmentally friendly!",
    "{A}: Don’t worry, I have a few knives up my sleeve.\n{B}: I think you mean cards.\n{A}, pulling knives out of their sleeves: No, I do not.",
    "{A}: I'm incredibly fast at math.\n{B}: Alright, what's 30x17?\n{A}: 47\n{B}: That's not even close.\n{A}: But it was fast.",
    "{A}: I’m gonna need a human skull and I can't have you ask any questions why.\n{B}: Only if you also don't ask why\n{B}: *Pulls out 7 pristine human skulls* Take your pick.\n{A}:\n{B}:\n{A}: This one is fine",
    "{A}: {B}...\n{B}: Oh no, '{B}' in b-flat.\n{B}: You're disappointed.",
    "{A}: i went through an entire character arc during quarantine\n{A}: i became more evil if you’re curious\n{B}: We're still in quarantine, don't worry, there's time for a redemption arc still!\n{A}: i’m going to get worse on purpose",
    "{A}: You're 'the second worst thing to ever happen to those orphans', what does that mean?\n{B}: It means i was second worst thing to happen to those orphans.\n{A}: but what’s the first worst thing?\n*Awkward pause*\n{B}: {A}, they...they weren’t always orphans.\n{A}:",
    "{A}: I'm 10 times funnier and sexier than you\n{B}: 10 times 0 is still 0 though\n{A}: Jokes on you, I can't do math",
    "{A}: Ok, maybe playing ‘whose family is most dysfunctional’ wasn’t the best idea we’ve had. {B}'s been crying in the bathroom for an hour. We can’t get them out...",
    "{A}: {B} was banned from the chicken shack, so we had to go out of town to get some.\n{B}: Well, they shouldn’t say “all you can eat” if they don’t mean it.\n{A}: {B}, you ate a chair.",
    "{A}: Here's some advice\n{B}: I didn't ask for any\n{A}: Too bad. I'm stuck here with my thoughts and you're the only one who talks to me",
    "{A}: Three words. Say them and I'm yours.\n{B}: Three words.\n{A}:",
    "{A}: Am I in trouble?\n{B}: Take a guess.\n{A}: No?\n{B}: Take another guess.",
    "{A}: How petty can you get?\n{B}: I once edited a Wikipedia article to win an argument I was wrong about.",
    "{A}: I turned out perfectly fine!\n{B}: {A}, this morning you thought a ghost made your toast\n{A}: <i>I</i> DIDN’T PUT THE BREAD IN! <i>YOU</i> DIDN’T PUT THE BREAD IN!!!",
    "{A}: Don’t worry, I know exactly what I’m doing. Everything is going to be fine!\n{B}: How can you still say that?\n{A}: Because sometimes, when things get tough, denial is all we have.",
    "*{A} and {B} are doing something absurdly dangerous*\n{A}: I think Houdini did something like this once! Why, if I recall correctly, he was out of the hospital in no time!\n{B}, deadpan: Well that's encouraging.",
    "{A}, talking to {B} on the phone: Did you preheat the oven like I told you to?\n{B}: You bet!\n{A}: At what temperature?\n{B}: 535.\n{A}: That's the clock.\n{B}:\n{A}:\n{B}: 536.",
    "{A}: I made tea.\n{B}: I don’t want tea.\n{A}: I did not make tea for you. This is my tea.\n{B}: Then why are you telling me?\n{A}: It is a conversation starter.\n{B}: That’s a lousy conversation starter.\n{A}: Oh, is it? We are conversing. Checkmate.",
    "{A}: So that’s my plan.\n{B}: Are you alright with constructive criticism? I don’t want to sound mean.\n{A}: No, go ahead, I want to hear it.\n{B}: It fucking sucks.\n{A}: That’s not constructive criticism.",
    "{A}, standing with their back turned: I’ve been expecting you, {B}.\n{B}: How did you do that without turning around?\n{A}: ... To be perfectly honest, the first couple of people I did that to were not you.",
    "{A}: Let’s watch Sharkboy and Lavagirl.\n{B}: Okay.\n{A}: And make out during the scary parts.\n{B}: Th-\n{B}: The scary parts.\n{B}: Of Sharkboy and Lavagirl.",
    "{A}: {B}, stop!  This isn't you, you've gone mad with power!\n{B}: Well of course I have.\n{B}: Have you ever tried going mad without power?\n{B}: It's boring.",
    "{A}: I'm a reverse necromancer.\n{B}: Isn't that just killing people?\n{A}: Ah, technicality.",
    "{A}: Can you keep a secret?\n{B}: Do you know anything about my life?\n{A}: No I do not. Good point.",
    "{A}: Remember when you didn't try to solve all your problems with attempted murder?\n{B}: Stop romanticizing the past.",
    "{A}: Today is a day of running through hurdles.\n{B}: Aren’t you supposed to jump OVER hurdles?\n{A}: Whatever. Fear is only something to be afraid of if you let it scare you.",
    "{A}: You saved me. I owe you my life.\n{B}: No thanks. I’ve seen it and I’m not very impressed.",
    "{A}: That’s one of my biggest fears. Like, if I ever woke up as a donut...\n{B}: You would eat yourself?\n{A}: I wouldn’t even question it.",
    "{A}: Violence isn't the answer.\n{B}: You’re right.\n{A}: *sighs in relief*\n{B}: Violence is the question.\n{A}: What?\n{B}, bolting away: And the answer is yes.\n{A}, running after them: NO-",
    "{A}: *Gets down on one knee*\n{B}: Oh my god, it’s finally happening.\n{A}: *Falls over*\n{B}: The poison is kicking in.",
    "{A}: What is your biggest weakness?\n{B}: I can be uncooperative.\n{A}: Okay, can you give me an example?\n{B}: No.",
    "{A}: If there's going to be a big dramatic scene, wait until I get back.\n{B}: Of course. I can't flip this table by myself.",
    "{A}: Okay, truth or dare?\n{B}: Truth\n{A}: How many hours have you slept this week?\n{B}:\n{B}: ...Dare\n{A}: Go to bed.\n{B}: I don’t like this game.",
    "{A}: In light of what you did for me, you can hug me for four to five seconds.\n{B}: FORTY FIVE SECONDS?!?\n{A}: No! Four to five seconds!\n{B}: Too late!!!",
    "{A}: English is a difficult language. It can be understood through tough thorough thought, though.\n{B}: You need to stop.",
    "{A}: Date someone who will drag you outside at 3am to look at the stars.\n{B}: If anyone, and I mean <i>anyone</i>, wakes me up at 3am to go look at the damn sky they will be removed indefinitely from my life.",
    "{A}: You're the love of my life and my best friend, I would do anything for you.\n{B}: I want you to eat three meals a day and have a decent sleep schedule.\n{A}: Absolutely not.",
    "{A}: Do you have any skeletons in your closet?\n{B}: You mean literally or figuratively?\n{A}: Honestly, the fact that I have to specify...",
    "{A}: What’s up guys? I’m back.\n{B}: What the- you can’t be here. You’re dead. I literally saw you die.\n{A}: Death is a social construct.",
    "{A}, going over {B}'s resume: Okay, so right here, it states that you’re creative.\n{B}: Yes\n{A}: Okay... may I know what you create?\n{A}: Problems.",
    "{A}: This is bothering me.\n{B}: Well, you <i>are</i> digging up a corpse.\n{A}: No, not that. That's, uh, pretty par for the course, actually.",
    "{A}: {B}! My face is on fire!\n{B}: {A}! Are you ok?!\n{A}: Oh yes, I'm fine. I just said that to make sure you'd come in here quickly.\n{B}: But your face <i>is</i> on fire.\n{A}: Yes. It's much faster than shaving.",
    "{A}: Fuck.\n{B}: We've got to work on your cursing.\n{A}: Why? I'm pretty good at cursing already.",
    "{A}: Do you take constructive criticism?\n{B}: I only take cash or credit.",
    "{A}: Name a more iconic duo than my crippling fear of abandonment and my anxiety. I'll wait.\n{B}: You and me!!!\n{A}, tearing up: Okay.",
    "{A}: I actually have a black belt.\n{B}: In what, karate?\n{A}: No, from Gucci.",
    "{A}: Someone will die.\n{B}: Of fun!",
    "{A}: I slept for almost 12 hours but I might still be tired so lets go for 12 more just incase.\n{B}: {A}, that's a coma.\n{A}: Sounds festive.",
    "{A}: You fuckers don’t know about my knife stick. It’s a knife taped to a stick and it’s the ultimate weapon.\n{B}, not looking up from their book: Spear.\n{A}: BLOCKED.",
    "{A}: *Kicks the door down looking panicked*\n{B}: What did you do?\n{A}: Nobody died.\n{B}: WHAT KIND OF ANSWER IS THAT?!",
    "{A}: Please, I'm begging you go to a doctor.\n{B}: I'm sorry is this OUR stab wound? Stay out of it.",
    "{A}: .. .----. -- / ... --- .-. .-. -.-- [translation: I’M SORRY]\n{B}: What's that?\n{A}: Remorse code.\n{B}: I'm even angrier now.",
    "{A}: Hey {B} can I get a sip of your water?\n{B}: It's not water.\n{A}: Vodka, I like your style!\n{B}: It's vinegar.\n{A}: Wh-Wha-\n{B}: It's vinegar, COWARD.",
    "{A}: How do I deal with my enemies?\n{B}: Kill them\n{A}: That's a bit extreme, I was hoping for a more passive solution\n{B}: Kill them only a little?",
    "{A}: This is such a bad idea.\n{B}: Then why are you coming along?\n{A}: One of us need to be able to talk the cops out of arresting us when this inevitably goes wrong.",
    "{A}: Do you think you’d actually notice if someone didn’t cast a shadow? Or if their limbs were just slightly too long? Or if they had just a little too many teeth? like how many times have you passed Something on the street and you just didn’t Notice It?\n{B}: Stay woke monsterfuckers ur love is out there!!!!!\n{A}: Yknow what? Not my point at all in any way whatsoever, but I’m glad I could be an inspiration.",
    "{A}: Okay. I get it. You've had a really hard time lately, you're stressed out, seven people died-\n{B}: Twelve, actually.\n{A}: Not the point. Look, they're dead now and really whose fault is that?\n{B}: Yours!\n{A}: That's right: no one's.",
    "{A}: What are your goals?\n{B}: To pet all the dogs.\n{A}: No, fitness goals.\n{B}: To be able to run fast enough to pet all the dogs.",
    "{A}: Change is inedible.\n{B}: Don't you mean inevitable?\n{A}, spitting out coins: No, I did not.",
    "{A}: *Accidentally hits {B} in the face*\n{A}: *Trying to decide between saying 'I’m fucking sorry' and 'Are you okay'*\n{A}: ARE YOU FUCKING SORRY?!\n{B}: What’s wrong with you?!",
    "{A}: I can explain.\n{B}: Can you?\n{A}: If you give me thirty seconds to think of a lie.",
    "{A}: Are you an ‘arr’ pirate, or a ‘yo ho ho’ pirate?\n{B}: I’m a ‘I’m not paying $600 for photoshop’ pirate.",
    "{A}, in a meeting: My policy is if you see something, say something.\n{B}: I saw a squirrel in a tree today!\n{A}, with the tone of someone who is used to {B}: Outstanding.\n{A}: This is what I’m talking about people.",
    "{A}: Must be hard not being able to laugh\n{B}: I do have a sense of humor you know\n{A}: I’ve never heard you laugh before\n{B}: I’ve never heard you say anything funny",
    "{A}: Whaddya call a fish with no eye?\n{B}, not looking up: Myxine Circifrons\n{A}:\n{A}: fsh",
    "{A}, struggling to keep upright in their 1 inch heels: Yeah, I-I don’t really think heels are for me\n{B}, pointing at them and walking flawlessly in sparkly golden 6 inch heels: WEAK.",
    "{A}: I know you’re deflecting by making jokes about how hot you are.\n{B}: It’s not a joke.\n{B}: *sniffles*\n{B}: I’m a legit snack.",
    "{A}: It’s dark in here\n{B}: Don’t worry dude I got this\n{B}: *Stomps their feet*\n{B}: *Skechers light up*",
    "{A}: I was arrested for being too cool.\n{B}: The charges were dropped due to a lack of supporting evidence.",
    "*{A} and {B} skipping stones on lake*\n{A}: It’s such a beautiful evening.\n{B}, whispering: Take that you fucking lake",
    "{A}: Oh just so you know, it's very muggy outside\n{B}:\n{B}: {A}, I swear, if I step outside and all of our mugs are on the front lawn...\n{A}: *Sips coffee from bowl*",
    "{A}: You kill people for money?!\n{B}: I can explain!\n{A}: And all this time I’ve been doing it for free like a chump!",
    "{A}: I prevented a murder today.\n{B}: Really? How’d you do that?\n{A}: self control.",
    "{A}: Sorry it took me so long to bail you out of jail\n{B}: No it’s my fault, I shouldn’t’ve used my one phone call to prank call the police",
    "{A}: So are we flirting right now?\n{B}: I AM LITERALLY STABBING YOU\n{A}: That doesn’t answer my question",
    "{A}: On a scale from “damn Daniel” to “fre sha vaca do”, how are you feeling? \n {B}: In between “it’s an avocado, thanks” and “how did you defeat Captain America”, but as a solid answer I would say “I don’t need a degree to be a clothing hanger”. How about you, {C}? \n {C}: Probably “road work ahead”. \n {D}: I speak many languages, and this is none of them.",
    "{A}: Yo is {D} sleeping or dead? \n {B}: Hopefully dead, I hated their guts. \n {C}: Yeah, so did I. \n {D}: Okay first of all, fuck you-",
    "{A}: I think we're missing something. \n {B}: Teamwork? \n {C}: Cohesion? \n {D}: A general sense of what we’re doing?",
    "{A}: Care for another sundae, weenie? \n {B}: I am not a weenie! \n {C}: Relax, you’re among friends. *raises their drink* \n {B}: My friends don’t hang out at Weenie Hut Jr’s. \n {D}: You tell ‘em, {B}! *sips their drink* \n {B}: {D}, what’re you doing here? \n {D}: I’m always here on Double Weenie Wednesdays.",
    "{A}: Have you seen a person named '{B}' around here? \n {C}: Ugh, yes. They made a horrible mess of the blood fountain. \n {D}: It looks fine to me? \n {C}: IT USED TO BE WATER!!!",
    "[The group is a prison cell that was just hit by an earthquake] \n {A}: Uh, I'm gonna roll a perception check of... 4, and see if our cell is, uh, in any way damaged by this quake \n {B}: You're in a prison cell :) \n {C}: You did great. Well, I got a 10- \n {B}: You're in a prison cell with bars on it :3 \n {D}: I got a 1! \n {B}: You're in... a cube-shaped place.",
    "{A}: Wake me up… \n {B}: Before you go go! \n {C}: When September ends… \n {D}: WAKE ME UP INSIDE-",
    "{A}: Truth or dare? \n {B}: Dare \n {A}: I dare you to kiss the hottest person in the room \n {B}: Hey {C} \n {C}, blushing: Yeah? \n {B}: Could you move? I’m trying to get to {D}",
    "{A}: Is stabbing someone immoral? \n {B}: Not if they consent to it. \n {C}: Depends who you’re stabbing. \n {D}: YES?!?",
    "Cop: You’re receiving a ticket for having three people on one motorcycle. \n {A}: Shit. \n {B}: Wait, three? \n Cop: Yeah? \n {C}: OH MY GOD {D} FELL OFF!!!",
    "{A}: How did none of you hear what I just said? \n {B}: I’ve been zoned out for the past two and a half hours. \n {C}: I got distracted about halfway through. \n {D}: Ignoring you was a conscious decision.",
    "{A}: Everyone, synchronize your watches. \n {B}: I don’t know how to do that. \n {C}: I don’t wear a watch. \n {D}: Time is a construct.",
    "{A}: Listen, I can explain... \n {B}: You’re making $500,000 and you’re only gonna pay me $30,000? \n {C}: You’re getting 30 grand? I’m getting $1,000! \n {D}: You guys are getting paid?",
    "{A}: I think {D} was right. \n {B}: I'm surprised they haven't marched in here to say 'I told you so.' \n {C}: They wouldn't do that. \n {D}: You're right, {C}. For once in your life, you're 100% right. I would never say that. \n {D}: *turns around, the shirt they're wearing says '{D} Told You So' on the back*",
    "{A}: Self care is actually getting into fights with randoms in dark alleys. \n {B}: No, self care is stuff like taking a bubble bath, or putting on a lot of makeup if you like it, or taking a nice warm nap! \n {C}: Self care is the burning heat when rage washes over you!! Self care is when you feel the bones crack under your powerful fists!! Self care is the fear in your enemies’ eyes!!! \n {D}: Lmao self care is taking your birthday cake just so I can eat the frosting. \n {A}: If you touch my birthday cake I’ll make you eat your hands.",
    "{A}: There is no future. there is no past. do you see? Time is simultaneous, an intricately structured jewel that humans insist on viewing one edge at a time, when the whole design is visible in every facet. \n {B}: \n {C}: \n {D}: \n Everyone Else At {A}’s Surprise Birthday Party: \n {B}: All I asked was if you wanted to cut your birthday cake first.",
    "{A}: Isn’t it weird that we pay money to see other people? \n {B}: Plane tickets? \n {C}: Concert tickets? \n {D}: Prostitution? \n {A}, holding their broken frames: Glasses.",
    "{A}: *Screams* \n {B}: *Screams louder to assert dominance* \n {C}: Should we do something?! \n {D}, observing: No, I want to see who wins this.",
    "{A}: You know those things will kill you, right? \n {B}, pouring another glass of whiskey: That’s the point. \n {C}, smoking a cigarette: We’re trying to speed up the process. \n {D}: *Nods while eating raw cookie dough*",
    "{A}: Hah! 69! You know what that means?\n{B}: What?\n{C}: That you're a child.\n{D}: HOW'D YOU GUESS MY IQ!?",
    "{A}: Why is {B} so sad?\n{C}: They took one of those “Which Character Are You?” quizzes\n{A}: And...?\n{B}: They got {D}.",
    "{A}: *Screams*\n{B}: *Screams louder to establish dominance*\n{C}: Should we do something?\n{D}: No, I want to see who wins.",
    "{A}: Dammit, {B}!\n{B}: What?! It wasn’t me!\n{A}: Sorry, force of habit. Dammit, {C}!\n{C}: Not me either.\n{A}: Oh...Then who set the house on fire?\n{D}: *whistles*",
    "{A}, banging on the door: {B}! Open up!\n{B}: Well, it all started when I was a kid...\n{C}: No, they meant-\n{D}: Let them finish.",
    "{C}: Why are {A} and {B} sitting with their backs to each other?\n{D}: They had a fight.\n{C}: Then why are they holding hands?\n{D}: They get sad when they fight.",
    "{A}, {B}, and {C} are sitting on a bench\n{D}: Why do you guys look so sad?\n{A}: Sit down with us so we can tell you.\n*{D} sits down*\n{B}: The bench is freshly painted.",
    "{A}: On the count of three, what's your favorite cake? One, two, three-\n{A} and {B}, in unison: Chocolate cake peanut butter frosting with chocolate chunks!\n{C}: Our turn, {D}! One, two, three- vanilla!\n{D}, deadpan: I've never had cake, what is cake.",
    "*{A}'s helping {B} out after they get injured, while the others are watching*\n{C}: How does {B} look?\n{D}: A little better than you, actually.",
    "{A}: *Trying to fill out legal paperwork stuff* Were you guys born AMAB or AFAB?\n{B}: Bold of you to assume I was born at all.\n{C}: I personally was created in a lab.\n{D}: I just straight up spawned lol.",
    "{A}, setting down a card: Ace of spades\n{B}, pulling out an Uno card: +4\n{C}, pulling out a Pokémon card: Jolteon, I choose you\n{D}, trembling: What are we playing",
    "{A}: Tonight, one of you will betray us.\n{B}: Is it me, {A}?\n{A}: No, it’s not you.\n{C}: Is it me, {A}?\n{A}: It’s not you either.\n{D}: Is it me, {A}?\n{A}:\n{A}, mockingly: Is IT mE {A}?",
    "{A}: You lying, cheating, piece of shit!\n{B}: Oh yeah? You’re the idiot who thinks you can get away with everything you do. WELCOME TO THE REAL WORLD\n{A}: I’m leaving you, and I’M TAKING {C} WITH ME\n{D}, picking up the monopoly board: I think we’re gonna stop playing now.",
    "{A}: You are now one day closer to eating your next plate of nachos.\n{B}: That's the most hopeful thing I've ever heard.\n{C}: But what if I die tomorrow and never eat any nachos?\n{D}: Then tomorrow is nacho lucky day.",
    "*{A} is cooking*\n{B}: Any chance that’s for me?\n{A}: It’s for {D}. I’m planning on making some bad choices tonight, and I need them on my side.\n {C}: I never realized the forethought that went into being a disappointment.",
    "{A}: *Gently taps table*\n{B}: *Taps back*\n{C}: What are they doing?\n{D}: Morse code.\n{A}: *Aggressively taps table*\n{B}: *Slams hands down* YOU TAKE THAT BACK-",
    "{A}: {B}, I'm sad.\n{B}: *Holds out arms for a hug* It’s going to be okay.\n{C}: {D}, I'm sad.\n{D}, nodding: mood.",
    "{A}: Can I be frank with you guys?\n{B}: Sure, but I don’t see how changing your name is gonna help.\n{C}: Can I still be {C}?\n{D}: Shh, let Frank speak.",
    "{A}: I currently have 7 empty notebooks and I have no clue what to put in them. Suggestions?\n{B}: Put spaghetti in it.\n{A}: I'm currently taking suggestions from literally anyone but you.\n{C}: Put spaghetti in it.\n{A}: I'm currently taking suggestions from anyone but you two.\n{D}: Put spaghetti in it.\n{A}: I'm no longer taking suggestions.",
    "{A}: I just ended a four year relationship.\n{B}: Oh, I’m so sorry. Are you okay?\n{A}: Hm? Oh yeah, I’m fine. It wasn’t my relationship.\n*{C} and {D} fighting from across the room*",
    "{A}: {B} isn’t answering their phone\n{C}: I’ll call\n{A}: {D} and I have both tried six times each, what makes you thi-\n{B}: Hello?",
    "{A}, about {B}: Apparently we’re getting someone new in the group.\n{C}: Are we stealing them?\n{D}: New or used?\n{A}: Wonderful responses, both of you.",
    "{A}: Why are your tongues purple?\n{C}: We had slushies. I had a blue one.\n{D}: I had a red one.\n{A}: oh\n{A}:\n{A}: OH\n{B}:\n{B}: You drank each other's slushies?",
    "{A}: {B} and I were crossing the street, and this dude drove by and honked at us \n {C}: *Sighing* What did {B} do? \n {A}: They chased him to the next red light, then reached into his window and... \n {B}: Who wants a steering wheel?",
    "{A}: What if I press the brake and gas at the same time? \n {B}: The car takes a screenshot. \n {C}: For the last time, get the fuck out.",
    "{A}: HELP! I TOLD {I} I’D COOK DINNER TONIGHT BUT I CAN’T COOK! \n {B}, pouring milk directly into the cereal bag: And you thought I could help?",
    "{A}: {B} and I don’t use pet names. \n {C}: I see. Hey, what do bees make? \n {A}: Honey? \n {B}: Yes, dear? \n {A}: \n {C}: Don't ever lie to my face again.",
    "{A}: I know you snuck out last night, {B}. \n {C}: Play dumb! \n {B}: Who's {B}? \n {C}: NOT THAT DUMB!!!",
    "{A}: {C} and I are having a baby. \n {B}: That's gre- \n {A}, slamming adoption papers on the table: It's you, sign here.",
    "*The group is getting into the car* \n {A}: I’m driving. \n {B}, out of view: Shotgun! \n {C}, turning to face {B}: Aww! But you had it on the way here- \n Everyone except {B}: WOAH- \n {B}, holding a shotgun: No! I found a shotgun! And I want the front seat! *Pumps gun*",
    "{A}: If you had to choose between {B} and all the money I have in my wallet, which would you choose? \n {C}: That depends, how much money are we taking about? \n {B}: {C}! \n {A}: 63 cents. \n {C}: I'll take the money. \n {B}: <b><i>{I}!!!</b></i>",
    "{A}: We need to get through this locked door. {B}, give me your credit card. \n {B}: Here. \n {A}, pocketing it: Thanks. {C}, kick down the door.",
    "{A}: You have to apologize to {B} \n {C}: Fine. \n {C}: 'Unfuck you' or whatever.",
    "{A}: Dandelions symbolize everything I want to be in life \n {B}: Fluffy and dead with a gust of wind? \n {A}: Unapologetic. Hard to kill. Feral, filled with sunlight, bright, beautiful in a way that the conventional and controlling hate but cannot ever fully destroy. Stubborn. Happy. Bastardous. Friends with bees. Highly disapproving of lawns. Full of wishes that will be carried far after I die. \n {C}: edible",
    "{A}: Fitness tip: never stop pushing yourself. Some say 8 hours of sleep is enough. Why not keep going? Why not 9? Why not 10? Strive for greatness. \n {B}: Next time you’re working out do 15 push ups instead of 10. Run 3 miles instead of 2. Eat a whole cake instead of just a slice. Burn your ex’s house down. You can do it. I believe in you. \n {C}: There were so many mixed messages in that I can’t-",    
    "{A}: Let me show you a picture from last night that really upset me \n {B}: Okay, but in my defense, {C} bet me 50 cents I couldn’t drink all that shampoo. \n {A}: That’s not what I wanted to- you drank SHAMPOO?!",
    "{A}: Are you the big spoon or the little spoon? \n {B}: I'm a knife. \n {C}, from across the room: They're the little spoon.",
    "{A}: Do you ever want to talk about your emotions, {B}? \n {B}: … No. \n {C}: I do! \n {A}: I know, {C}. \n {C}: I’m sad! \n {A}: I know, {C}.",
    "{A}: Who thinks I can fit 15 marshmallows in my mouth? \n {B}: You’re a hazard to society \n {C}: And a coward. DO TWENTY.",
    "{A}: Come on, I wasn’t that drunk last night. \n {B}: You were flirting with {C}. \n {A}: So what? They're my partner. \n {B}: You asked them if they were single. \n {A}: \n {B}: And then you cried when they said they weren't.",
    "{A}: What time is it? \n {B}: I don’t know; pass me that saxophone and we’ll find out \n {B}: *Plays sax loudly and extremely out of tune* \n {C}: WHO THE FUCK IS PLAYING THE SAXOPHONE AT TWO IN THE MORNING \n {B}: It’s 2 am",
    "{A}: In my defense, I was left unsupervised. \n {B}: Wasn't {C} with you? \n {C}: In my defense, I was also left unsupervised.",    
    "{A}: I can’t believe you live nearby, and you won’t let anyone crash at your place. \n {B}: You people already know too much about me. \n {C}: I know exactly three facts about you, and one of them is that you won’t let any of us crash at your place.",
    "{A}: Would you stab your best friend in the leg for 10 million gold? \n {B}: You stab me, and then when my leg gets better, we buy a big-ass house. \n {C}: You can stab me too, then we'll have 20 million. \n {B}: Good thinking.",
    "{A}: If I die, my funeral is going to be the biggest party ever and you’re all invited \n {B}: If? \n {C}: Great, the only party I’ve ever been invited to and they might not even die.",
    "{A}, holding a python: Guys I impulsively bought a snake, what do I name him \n {B}: You did WHAT– \n {C}: William Snakepeare",
    "*The squad is having dinner together*\n{A}: {B}, can you pass the salt?\n{B}: *Throws {C} across the table*",
    "{A}: How's the sexiest person here~?\n{B}: I don't know, how are they~?\n{A}, flustered: I-\n{C}, from across the room: I'm doing great, thanks!",
    "{A}, whispering to {B}, who’s on the phone with {C}: Ask them something!\n{B}: How are you feeling?\n{C}: Fine.\n{A}: Something personal!\n{B}: At what age did you first get your period?",
    "{A}: I trust {B}.\n{C}: You think they know what they're doing?\n{A}: I wouldn't go that far.",
    "{A}: They stole from me first!\n{B}: Mhm.\n{A}: Stole my heart...\n{C}: It is still illegal to commit murder.",
    "{A}: Don't worry, I got a plan.\n{B}: Alright.\n{A}: TraitorSayWhat?\n{C}: Excuse me?\n{A}: What?\n{B}:\n{A}:\n{A}: No wait-",
    "{A}: Hey, {B}? Can I get some dating advice?\n{B}: Just because I’m with {C} doesn’t mean I know how I did it.",
    "The squad is trying to con some random guy\n{A}: Um, {B}, why are you pretending I'm this guy's family?\n{B}: We need money!\n{A}: You're scamming him?\n{B}: I was thinking more like flat-out stealing from him?\n{A}: What?! No way!\n{B}: Why not? We already stole {C}!\n{C}: Hey guys\n{A}: No, we didn't. {C} can think and talk for themself, they can do whatever they want!\n{C}: I wanna steal",
    "{A}: Why are you on the floor?\n{B}: I'm depressed.\n{B}: Also I was stabbed, can you get {C}, please.",
    "*The squad is talking about what it'd be like to open up a homemade Pokemon gym*\n{A}, joking: {B}'s just sitting at the end, juggling- fushigi-ing 2 glass balls, in super tight pants, just waiting for their kid delivery once they best their minions.\n{B}: Well they would be Pokeballs. And also it's not a kid delivery. There's no fucking guarantee that a kid that comes into the <i>beginning</i> of my crucible makes it to the <i>end</i> of it undefeated.\n{B}: In fact, I'm gonna stack this gym! With fuckin pros!\n{B}: It's- It's gonna be brutal. It's gonna be a torture gym.\n{C}: Well- Well what's the theme? Are you like- is it a bug theme, or like-\n{B}: YEAH, {I}. UH- UH- UH- UH YEAH {I}. IM GONNA OPEN UP A <i>BUG TYPE</i> POKEMON GYM. YOU <i><b>IDIOT</i></b>.\n{B}: YEAH THAT'S WHAT I WANT, BECAUSE I WANNA GIVE- I WANNA SHIT OUT BADGES FOR EVERY HAM AND EGGER THAT COMES TO MY FRONT DOOR.\n{A}: *Cracking up*\n{B}: YEAH, {I}. 'Uhh, go Caterpie! >~>' That's me, you FUCKING imbecile. 'Yeah go- uhhh- d-do your best, Kakuna!'\n{B}: WHAT ARE YOU FUCKING TALKING ABOU- Yeah a ~bug type~ gym.\n{C}:\n{A}: Okaaay-\n{C}: Alright, um, I'm gonna go. I've embarrassed myself...\n{A}: Maybe fire? Fire type?\n{C}: Yeah fire-based? Like- have fires?{B}: Yeah, yeah I'll probably just- That's a good idea {A} I'll probably just do a fire type one... SO THAT <i>ONE</i> KID WITH <i>ONE</i> BLASTOISE CAN FUCK UP MY WHOLE SHOP.\n{B}: KILLED ALL OF US WITH ONE BLASTOISE, HUH? WOW. SHIT I SHOULD'VE-\n{C}: Just do rock, then! Just do rock type!\n{B}, voice dripping with contempt: <i><b>The same Blastoise...</i></b>",
    "{A}: Are you sure this is the right direction?\n{B}: Certainly, I'm as sure as I am honest!\n{C}: In that case, we're <i>definitely</i> lost.",
    "{A}: Naturally, <i>we</i> are on the cutting edge of technology.\n{B}, amazed: Wow...\n{C}, to {B}: Well what does that mean?\n{B}: I don't know.\n{B}, to {A}: What does that mean?",
    "{A}, trying to ask {B} out: Would you like to stay for dinner?\n{C}: WOULD YOU LIKE TO STAY FOREVER?",
    "{A}: We need a distraction.\n{B}: Is anyone here good at jumping up and down and making weird noises?\n{C}, whispering: My time has come",
    "*{A} and {B} sitting in jail together*\n{B}: So who should we call?\n{A}: I’d call {C}, but I feel safer in jail",
    "{A}: I really like this whole ‘good guy, bad guy’ thing you guys have going on.\n{B}: It’s not an act, it’s just that I’m mean and {C} isn’t",
    "{A}: WHY. why did you give {C} a KNIFE?!\n{B}: I’m sorry. They said they felt unsafe.\n{A}: Now <i>I</i> feel unsafe!\n{B}: I’m sorry.\n{B}: ... would you like a knife?", 
    "{A}: {B}, keep an eye on {C} today. They're going to say something to the wrong person and get punched.\n{B}: Sure, I’d love to see {C} get punched.\n{A}: Try again.\n{B}, sighing: I will stop {C} from getting punched.",
    "{A}, negotiating with {B}: We have {C}. Give us ten thousand dollars and they will be returned to you unharmed\n{C}: Whoa, whoa, wait, you think I’m only worth ten thousand dollars?\n{A}:\n{C}: MAKE IT ONE MILLION–\n{A}: {I} STOP",
    "{A}: Here’s a fun Christmas idea. We hang mistletoe, but instead of kissing, you have to FIGHT whoever else is under it.\n{B}: {A} no.\n{C}: Mistlefoe.\n{B}: Please stop encouraging them.",
    "{A}, to {B}: My life is in the hands of an idiot!\n{B}, motioning to themself and {C}: No no no no no, TWO idiots!",
    "{A}: In your opinion, what’s the height of stupidity?\n{B}: *turning to {C}* How tall are you?",
    "{A}: I love you guys, you're the best thing that's happened to me.\n{B}: We're the best thing that's ever happened to you?\n{A}: Yes!\n{C}: I'm starting to feel a little sorry for you.",  
    "{A}: Tell {B} about the birds and the bees.\n{C}: They're disappearing at an alarming rate.",
    "{A}, at a restaurant: You guys should get the orange soda, it's amazing.\n{B}: Okay\nWaiter: Can I get you guys anything to drink?\n{A}: Orange soda, please!\n{B}: I'll have the strawberry soda.\n{C}: Me too, strawberry soda.\n{A}:",
    "{A}: So, what, now I’m just supposed to do anything that {B} does? I mean, what if they jumped off a cliff?\n{C}: If {B} were to jump off a cliff, they would’ve done their due diligence regarding the height of the cliff, the depth of the water, and the angle of entry, so yes. If you see {B} jump off a cliff, by all means, jump off a cliff.\n{A}: <i>You</i> jump off a cliff!\n{C}: Gladly. Provided {B} did first.",
    "{A}: {C}, can I talk to you for a second?\n{C}: Yeah, what’s up? Lemme guess. You and {B} are having problems and you want me to teach you how to kiss?\n{A}: What? No, stop that. I know how to kiss. I’ve read books.",
    "{A}: What do you think {B} will do for a distraction?\n{C}: They’ll probably, like, make a noise or throw a rock. That’s what I would do.\n*Building explodes and several car alarms go off*\n{C}: ... or they could do that.",    
    "{A}: What's a word thats a mix between 'sad' and 'mad'?\n{B}: Disgruntled, miserable, desolated-\n{C}: Smad.",
    "{A}: Please bring home PURIFIED water with NO minerals added for taste\n{B}: We got spring water\n{A}: NO.\n{C}: with EXTRA minerals\n{B}: it's like licking a stalagmite\n{A}: DON'T COME HOME.\n{C}: Mmmmm cave water",
    "{A}: If I accidentally sat on a voodoo doll of myself, would I be trapped forever in that position, doomed to starve to death?\n{B}: How am I supposed to know?\n{C}: You say, as if we don’t use you as a source of knowledge of the occult.\n{B}: *sighs*\n{B}: You wouldn't be trapped.",
    "{A}, driving {B} and {C}: So how was your day?\n{B}: We almost got surprise adopted!\n{A}: What?\n{C}: We almost got kidnapped.\n{A}: Oh, okay.\n{A}: *slams on the breaks* WAIT WHAT?!",
    "{A}: While I’m gone, {B}, you’re in charge.\n{B}: Yes!!!\n{A}, whispering: {C}, you’re secretly in charge.\n{C}: Obviously.",
    "{A}: {B}, what do IDK, LY, and TTYL mean?\n{B}: I don’t know, love you, talk to you later\n{A}: Ok, I love you too, I’ll just ask {C}.",
    "{A}: Sometimes I drink milk straight out of the container.\n{B}: The cow???\n{A}: What?\n{C}: {B}, W H Y?",
    "{A}: {C}, my old arch enemy.\n{B}: ... I thought I was your arch enemy?\n{A}: I have a life outside of you, {B}.",
    "{A}: What did you do with {C}'s body?\n{B}: What didn’t I do with the body?\n{A}:\n{B}: Okay, that sounded more sexual than I intended. I disposed of the corpse respectfully.",
    "{A}, in a high voice, holding barbie: hey ken! I was thinking about going back to school and starting a career!\n{B}, in a deep voice, holding ken: nonsense, barbie. you’re staying home and having my kids\n{C}: what the fuck are you guys doing?\n{A}: playing systemic oppression",
    "Store Worker: Would a Mx. {A} please come to the front desk?\n{A}, arriving at the desk: Hello, is there a problem?\nStore Worker: points to {B} and {C}\nStore Worker: I believe they belong to you?\n{B} and {C}, simultaneously: We got lost :(\n{A}: I didn’t even bring you guys here with me-",
    "{A}, texting {B}: {B}! Help I’m being kidnapped\n{C}: Where are you?\n{A}: I’m with some strange person. In a car. Help.\n{B}: I’ll call {C}.\n{C}, answering their cell: Y’ello?\n{B}: Where’s {A}? They texted me that they were being kidnapped.\n{C}: {A}? Whaddya mean, they're right next to me-\n{C}:\n{C}: I’ll call you back. *hangs up*\n{C}: THE NEW HAIRCUT ISN’T THAT BAD!\n{A}: WHO ARE YOU?!",
    "{A}: I told {B} their ears flush when they lie.\n{C}: Why?\n{A}: Look.\n{A}: Hey {B}! Do you love us?\n{B}, covering their ears: No.\n{C}:",
    "{A}: I’m kind of crushing on someone, but I’m worried about telling you who it is, because you’re not going to like it\n{B}: Just rip the bandage off.\n{A}: It’s {C}.\n{B}: Put the bandage back on.",
    "{A}: If {B} and I were drowning, who would you save?\n{C}: You two can’t swim?\n{B}: It’s a hypothetical question, {C}! who would you save?\n{C}: my time and effort.",
    "{A}: Hey {B},\n{B}: Yes?\n{A}: Can a person breathe inside a washing machine while it’s on?\n{B}:\n{B}: Where’s {C}?",
];

var A = "Venti";
var B = "Zhongli";
var C = "Ei";
var D = "Kusanali";

var E = A.toUpperCase();
var F = B.toUpperCase();
var G = C.toUpperCase();
var H = D.toUpperCase();

var R = Math.floor(Math.random() * prompts.length);
var str = prompts[R];
var result = str
    .replace(/{A}/g, A)
    .replace(/{B}/g, B)
    .replace(/{C}/g, C)
    .replace(/{D}/g, D)
    .replace(/{F}/g, F)
    .replace(/{G}/g, G);
// End of prompt generation

var today = new Date();
var title =
    "Posted date: " +
    today.getFullYear() +
    "-" +
    (today.getMonth() + 1) +
    "-" +
    today.getDate() +
    "\n";

fb.api("me/feed", "post", { message: title + result }, function (res) {
    if (!res || res.error) {
        console.log(!res ? "error occurred" : res.error);
        return;
    }
    console.log("Post Id: " + res.id);
});
